### ISSUE TITLE
Using GPS info in Car 

### ISSUE THREAD

**Issue by thejeshk** [JeremyBYU/airsimgeo#1]
Hello JeremBYU, 

I am a Master student from TU Kaiserslautern, Germany. 

Sorry if this issue if bit offtopic. 
I have opened this issue because I see that knew so much about co-ordinated systems and the plugin which you have developed. 

About me: I am doing a project where I have to create a custom environment in Unreal engine which look like (see image). 

Question 1: Is it possible to Spawn my vehicle at specific GPS position 

Question 2: How does your lug in relate to the vehicle that I ma using. I am using Car like vehicle
![point_of_interest_HBR](https://user-images.githubusercontent.com/33362523/76301589-cc5a4e00-62be-11ea-86ce-5f5b46991b14.PNG)

![HBR_site_demo](https://user-images.githubusercontent.com/33362523/76301693-f6137500-62be-11ea-98e4-85a2be447914.PNG)

**Comment by JeremyBYU** [comment]
1. Yes you can spawn at a specific gps position
2. I think "lug" was plugin?  It looks like my plugin only extended the multirotor client. However the functions it uses are generic and should work with  the car Class as well.

I wrote a blog post about this process here. 
https://robosim.dev/

Maybe it might help?
